{% set name = "napari-pystackreg" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_pystackreg-{{ version }}.tar.gz
  sha256: ea3fb0b3ecc7b90b64f44c1ced4a85a6cf8231b07e5985ad59a6c1c152cd4cb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - napari
    - numpy
    - pystackreg >=0.2.6
    - python >={{ python_min }}
    - qtpy
    - scikit-image

test:
  imports:
    - napari_pystackreg
    - napari_pystackreg._widget
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glichtner/napari-pystackreg
  summary: Robust image registration for napari
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - glichtner
    - goanpeca
    - jaimergp
